version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requires 1234
volumes:
  redis_data: